---
functional:
  - Пользователи могут регистироваться на сайте (возможно, описать разные способы регистрации, требования к данным (например, к паролям)?)
  - Пользователи могут авторизовываться с существующими аккаунтами
  - Пользователи могут играть с ботами
  - Пользователи могут играть с другими пользователями
  - Пользователи могут приглашать в игру других пользовптели по ссылке
  - Пользователи могут присоединяться к игре по ссылке
  
  - Когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно, где написано, выиграл игрок или проиграл
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Игра поддерживает различные языки программирования
implicit:
  - Мне кажется странным, что для задач есть перевод на русский язык, а для интерфейса нет
  - требование 6
